# Generated by Django 5.0.4 on 2024-04-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_descriptions_sushi_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sushi',
            old_name='Name',
            new_name='name',
        ),
    ]
