# Generated by Django 5.0.4 on 2024-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sushi_price_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushi',
            name='price',
            field=models.FloatField(),
        ),
    ]
